name: Sample Workflow

on: [ workflow_dispatch, push ]


jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Run commands
        run: |
          cat /etc/hosts
          cat /etc/resolv.conf
          ip a
          ip r
